CC = g++
STD = --std=c++17

clean:
	@rm -f [0][1-9].exe [1][0-4].exe

all: 01 02 03 04 05 06 07 08 09 10 11 12 13 14

01:
	$(CC) -o 01.exe src01.cpp $(STD)

02:
	$(CC) -o 02.exe src02.cpp $(STD)

03:
	$(CC) -o 03.exe src03.cpp $(STD)

04:
	$(CC) -o 04.exe src04.cpp $(STD)

05:
	$(CC) -o 05.exe src05.cpp $(STD)

06:
	$(CC) -o 06.exe src06.cpp $(STD)

07:
	$(CC) -o 07.exe src07.cpp $(STD)

08:
	$(CC) -o 08.exe src08.cpp $(STD)

09:
	$(CC) -o 09.exe src09.cpp $(STD)

10:
	$(CC) -o 10.exe src10.cpp $(STD)

11:
	$(CC) -o 11.exe src11.cpp $(STD)

12:
	$(CC) -o 12.exe src12.cpp $(STD)

13:
	$(CC) -o 13.exe src13.cpp $(STD)

14:
	$(CC) -o 14.exe src14.cpp $(STD)